#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

export BITCOIN_CONF="/etc/chain2/bitcoin.conf"

# add random rpc password to bitcoin.conf, if there isn't one.
if ! grep -q '^rpcpassword=' $BITCOIN_CONF; then
    echo "Adding a random rcp password to $BITCOIN_CONF"
    echo "rpcpassword=$(xxd -l 17 -p /dev/urandom)" >> $BITCOIN_CONF
fi

# add users
adduser --system --group --quiet bitcoin

# cleanup permissions
chown root:root /usr/bin/chain2*
chown root:root /lib/systemd/system/chain2d.service
chown root:root /etc/chain2
chown bitcoin:bitcoin /etc/chain2/bitcoin.conf
chmod ug+r /etc/chain2/bitcoin.conf 
chmod u+w /etc/chain2/bitcoin.conf
chmod o-rw /etc/chain2/bitcoin.conf 
chown -R bitcoin:bitcoin /var/lib/chain2
chmod u+rwx /var/lib/chain2

# enable and start chain2d service if systemctl exists and is executable
if [ -x "/bin/systemctl" ]; then
    db_input high chain2/start_service || true
    db_go || true
    db_get chain2/start_service 
    if [ "$RET" = "true" ]; then
        echo "Enabling chain2d.service"
    	/bin/systemctl enable chain2d.service
        echo "Starting chain2d.service"
    	/bin/systemctl start chain2d.service
    else
        echo "The chain2d.service NOT enabled or started."
    fi
else
    echo "The file '/bin/systemctl' is not executable or found, chain2d service not automatically enabled or started" 
fi
