#!/bin/sh -e

# stop and disable chain2d service if systemctl exists and is executable
if [ -x "/bin/systemctl" ]; then
    echo "Stopping chain2d.service"
    /bin/systemctl stop chain2d.service
    echo "Disabling chain2d.service"
    /bin/systemctl disable chain2d.service
fi
